### ISSUE TITLE
升级到 clean-css 3.0.7 后，fis release -omp 会出现异常。

### ISSUE THREAD

**Issue by aftdotleo** [xiangshouding/fis-optimizer-clean-css-2x#1]
Hi @xiangshouding ，

fis-optimizer-clean-css-2x 更新后（升级到 clean-css 3.0.7 ），fis release -omp 会出现异常。

异常提示：
 [ERROR] optimizer.clean-css-2x: object is not a function 

not a string or not a buffer...

问题原因：
可见 https://github.com/jakubpawlowicz/clean-css#user-content-how-to-use-clean-css-programmatically

``` js
var minified = new CleanCSS().minify(source).styles; 
```

所以
index.js:

``` js
module.exports = function(content, file, conf){
    conf.processImport = false;
    return new CleanCss(conf).minify(content).styles;
};
```

**Comment by oxUnd** [comment]
@aftdotleo OK，感谢；

**Comment by oxUnd** [comment]
done 新发了下，版本 0.2.1

**Comment by aftdotleo** [comment]
赞！
